### ISSUE TITLE
DAC reference

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Phaser#8]
internal or external ?

**Comment by gkasprow** [comment]
@hartytp any opinion here?

**Comment by hartytp** [comment]
Internal

**Comment by hartytp** [comment]
Because AFAICT the only thing the ref does is reduce the temp co from 30ppm/K to 15ppm/K. That’s not enough difference to be worth it. In any case it’s hard to build a complete rf chain with 15ppm/K stability (we did a lot of careful work on this recently and even short lengths of coax can be worse than that)

**Comment by hartytp** [comment]
Tbh I don’t know why they even bother giving the user this option

One thing though: if you can please add a big bypass cap to filter the internal ref

**Comment by gkasprow** [comment]
OK
